//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookHeaven.Server.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookHeaven.Server.Localization.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add cover.
        /// </summary>
        public static string ADD_COVER {
            get {
                return ResourceManager.GetString("ADD_COVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string AUTHOR {
            get {
                return ResourceManager.GetString("AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string AUTHORS {
            get {
                return ResourceManager.GetString("AUTHORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string BOOK {
            get {
                return ResourceManager.GetString("BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string BOOKS {
            get {
                return ResourceManager.GetString("BOOKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books from.
        /// </summary>
        public static string BOOKS_FROM {
            get {
                return ResourceManager.GetString("BOOKS_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date format.
        /// </summary>
        public static string DATE_FORMAT {
            get {
                return ResourceManager.GetString("DATE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string DONE {
            get {
                return ResourceManager.GetString("DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string DOWNLOAD {
            get {
                return ResourceManager.GetString("DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string END_DATE {
            get {
                return ResourceManager.GetString("END_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string GO_BACK {
            get {
                return ResourceManager.GetString("GO_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last read.
        /// </summary>
        public static string LAST_READ {
            get {
                return ResourceManager.GetString("LAST_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long date format.
        /// </summary>
        public static string LONG_DATE_FORMAT {
            get {
                return ResourceManager.GetString("LONG_DATE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string PROFILES {
            get {
                return ResourceManager.GetString("PROFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your first profile.
        /// </summary>
        public static string PROFILES_CREATE_FIRST {
            get {
                return ResourceManager.GetString("PROFILES_CREATE_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage profiles.
        /// </summary>
        public static string PROFILES_MANAGE {
            get {
                return ResourceManager.GetString("PROFILES_MANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your profile.
        /// </summary>
        public static string PROFILES_SELECT {
            get {
                return ResourceManager.GetString("PROFILES_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string PROGRESS {
            get {
                return ResourceManager.GetString("PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        public static string PUBLISHED {
            get {
                return ResourceManager.GetString("PUBLISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string PUBLISHER {
            get {
                return ResourceManager.GetString("PUBLISHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Time.
        /// </summary>
        public static string READ_TIME {
            get {
                return ResourceManager.GetString("READ_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace cover.
        /// </summary>
        public static string REPLACE_COVER {
            get {
                return ResourceManager.GetString("REPLACE_COVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string SERIES {
            get {
                return ResourceManager.GetString("SERIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series Index.
        /// </summary>
        public static string SERIES_INDEX {
            get {
                return ResourceManager.GetString("SERIES_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string SERIES_PLURAL {
            get {
                return ResourceManager.GetString("SERIES_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf.
        /// </summary>
        public static string SHELF {
            get {
                return ResourceManager.GetString("SHELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your shelf is empty.
        /// </summary>
        public static string SHELF_EMPTY {
            get {
                return ResourceManager.GetString("SHELF_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No books matching the selected filter.
        /// </summary>
        public static string SHELF_FILTER_NO_RESULTS {
            get {
                return ResourceManager.GetString("SHELF_FILTER_NO_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string START_DATE {
            get {
                return ResourceManager.GetString("START_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading book.
        /// </summary>
        public static string UPLOADING_BOOK {
            get {
                return ResourceManager.GetString("UPLOADING_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload book.
        /// </summary>
        public static string UPLOADING_BOOK_FAILED {
            get {
                return ResourceManager.GetString("UPLOADING_BOOK_FAILED", resourceCulture);
            }
        }
    }
}
