//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookHeaven.Server.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookHeaven.Server.Localization.Translations.es", typeof(Translations_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        public static string ACTIONS {
            get {
                return ResourceManager.GetString("ACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir portada.
        /// </summary>
        public static string ADD_COVER {
            get {
                return ResourceManager.GetString("ADD_COVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        public static string AUTHOR {
            get {
                return ResourceManager.GetString("AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor eliminado correctamente..
        /// </summary>
        public static string AUTHOR_DELETED {
            get {
                return ResourceManager.GetString("AUTHOR_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar el autor si tiene libros asociados.
        /// </summary>
        public static string AUTHOR_NOT_EMPTY {
            get {
                return ResourceManager.GetString("AUTHOR_NOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autores.
        /// </summary>
        public static string AUTHORS {
            get {
                return ResourceManager.GetString("AUTHORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libro.
        /// </summary>
        public static string BOOK {
            get {
                return ResourceManager.GetString("BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libros.
        /// </summary>
        public static string BOOKS {
            get {
                return ResourceManager.GetString("BOOKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libros de.
        /// </summary>
        public static string BOOKS_FROM {
            get {
                return ResourceManager.GetString("BOOKS_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esto no se puede deshacer..
        /// </summary>
        public static string CANNOT_BE_UNDONE {
            get {
                return ResourceManager.GetString("CANNOT_BE_UNDONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de fecha.
        /// </summary>
        public static string DATE_FORMAT {
            get {
                return ResourceManager.GetString("DATE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar autor.
        /// </summary>
        public static string DELETE_AUTHOR {
            get {
                return ResourceManager.GetString("DELETE_AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿De verdad quieres eliminar este autor?.
        /// </summary>
        public static string DELETE_AUTHOR_CONFIRM_MESSAGE {
            get {
                return ResourceManager.GetString("DELETE_AUTHOR_CONFIRM_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar serie.
        /// </summary>
        public static string DELETE_SERIES {
            get {
                return ResourceManager.GetString("DELETE_SERIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿De verdad quieres eliminar esta serie?.
        /// </summary>
        public static string DELETE_SERIES_CONFIRM_MESSAGE {
            get {
                return ResourceManager.GetString("DELETE_SERIES_CONFIRM_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listo.
        /// </summary>
        public static string DONE {
            get {
                return ResourceManager.GetString("DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar.
        /// </summary>
        public static string DOWNLOAD {
            get {
                return ResourceManager.GetString("DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Fin.
        /// </summary>
        public static string END_DATE {
            get {
                return ResourceManager.GetString("END_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        public static string GO_BACK {
            get {
                return ResourceManager.GetString("GO_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última lectura.
        /// </summary>
        public static string LAST_READ {
            get {
                return ResourceManager.GetString("LAST_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de fecha largo.
        /// </summary>
        public static string LONG_DATE_FORMAT {
            get {
                return ResourceManager.GetString("LONG_DATE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva serie.
        /// </summary>
        public static string NEW_SERIES {
            get {
                return ResourceManager.GetString("NEW_SERIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear perfil.
        /// </summary>
        public static string PROFILE_CREATE {
            get {
                return ResourceManager.GetString("PROFILE_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿De verdad quieres eliminar este perfil? Perderás el progreso de todos los libros para este perfil. Esta acción no se puede deshacer..
        /// </summary>
        public static string PROFILE_DELETE_WARNING_MESSAGE {
            get {
                return ResourceManager.GetString("PROFILE_DELETE_WARNING_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar perfil.
        /// </summary>
        public static string PROFILE_EDIT {
            get {
                return ResourceManager.GetString("PROFILE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfiles.
        /// </summary>
        public static string PROFILES {
            get {
                return ResourceManager.GetString("PROFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea tu primer perfil.
        /// </summary>
        public static string PROFILES_CREATE_FIRST {
            get {
                return ResourceManager.GetString("PROFILES_CREATE_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrar perfiles.
        /// </summary>
        public static string PROFILES_MANAGE {
            get {
                return ResourceManager.GetString("PROFILES_MANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona tu perfil.
        /// </summary>
        public static string PROFILES_SELECT {
            get {
                return ResourceManager.GetString("PROFILES_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progreso.
        /// </summary>
        public static string PROGRESS {
            get {
                return ResourceManager.GetString("PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Publicación.
        /// </summary>
        public static string PUBLISHED {
            get {
                return ResourceManager.GetString("PUBLISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editorial.
        /// </summary>
        public static string PUBLISHER {
            get {
                return ResourceManager.GetString("PUBLISHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo.
        /// </summary>
        public static string READ_TIME {
            get {
                return ResourceManager.GetString("READ_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recargar página.
        /// </summary>
        public static string RECONNECT_MODAL_BUTTON_RECONNECT {
            get {
                return ResourceManager.GetString("RECONNECT_MODAL_BUTTON_RECONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reanudar sesión.
        /// </summary>
        public static string RECONNECT_MODAL_BUTTON_RESUME {
            get {
                return ResourceManager.GetString("RECONNECT_MODAL_BUTTON_RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha pausado la sesión por inactividad..
        /// </summary>
        public static string RECONNECT_MODAL_INFO_PAUSE {
            get {
                return ResourceManager.GetString("RECONNECT_MODAL_INFO_PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconectando con el servidor....
        /// </summary>
        public static string RECONNECT_MODAL_INFO_RECONNECT {
            get {
                return ResourceManager.GetString("RECONNECT_MODAL_INFO_RECONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha podido reanudar la conexión.&lt;br/&gt;Por favor, recarga la página..
        /// </summary>
        public static string RECONNECT_MODAL_INFO_RECONNECT_FAILED {
            get {
                return ResourceManager.GetString("RECONNECT_MODAL_INFO_RECONNECT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recargando la página....
        /// </summary>
        public static string RECONNECT_MODAL_INFO_RESUME_FAILED {
            get {
                return ResourceManager.GetString("RECONNECT_MODAL_INFO_RESUME_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexión fallida... reintentando en {0} segundos..
        /// </summary>
        public static string RECONNECT_MODAL_INFO_RETRYING {
            get {
                return ResourceManager.GetString("RECONNECT_MODAL_INFO_RETRYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reemplazar portada.
        /// </summary>
        public static string REPLACE_COVER {
            get {
                return ResourceManager.GetString("REPLACE_COVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie.
        /// </summary>
        public static string SERIES {
            get {
                return ResourceManager.GetString("SERIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Índice.
        /// </summary>
        public static string SERIES_INDEX {
            get {
                return ResourceManager.GetString("SERIES_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la serie no puede estar vacío.
        /// </summary>
        public static string SERIES_NAME_CANT_BE_EMPTY {
            get {
                return ResourceManager.GetString("SERIES_NAME_CANT_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string SERIES_PLURAL {
            get {
                return ResourceManager.GetString("SERIES_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajustes.
        /// </summary>
        public static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estantería.
        /// </summary>
        public static string SHELF {
            get {
                return ResourceManager.GetString("SHELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu estantería está vacía.
        /// </summary>
        public static string SHELF_EMPTY {
            get {
                return ResourceManager.GetString("SHELF_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay libros que coincidan con el filtro actual.
        /// </summary>
        public static string SHELF_FILTER_NO_RESULTS {
            get {
                return ResourceManager.GetString("SHELF_FILTER_NO_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Inicio.
        /// </summary>
        public static string START_DATE {
            get {
                return ResourceManager.GetString("START_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subiendo libro.
        /// </summary>
        public static string UPLOADING_BOOK {
            get {
                return ResourceManager.GetString("UPLOADING_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha podido cargar el libro.
        /// </summary>
        public static string UPLOADING_BOOK_FAILED {
            get {
                return ResourceManager.GetString("UPLOADING_BOOK_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libro cargado correctamente.
        /// </summary>
        public static string UPLOADING_BOOK_SUCCESS {
            get {
                return ResourceManager.GetString("UPLOADING_BOOK_SUCCESS", resourceCulture);
            }
        }
    }
}
