name: Build and push docker image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: bookheaven/bookheaven-server

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Move Server to BookHeaven directory
      run: |
        mkdir -p BookHeaven/BookHeaven.Server
        shopt -s extglob
        mv !(BookHeaven) BookHeaven/BookHeaven.Server/

    - name: Clone EpubManager
      run: |
        git clone https://${{ secrets.PAT_TOKEN }}@github.com/HeasHeartfire/EpubManager.git temp/EpubManager
        mkdir -p BookHeaven/EpubManager
        mv temp/EpubManager/* BookHeaven/EpubManager/
        
    - name: Clone BookHeaven.Domain
      run: |
        git clone https://${{ secrets.PAT_TOKEN }}@github.com/BookHeaven/BookHeaven.Domain.git temp/BookHeaven.Domain
        mkdir -p BookHeaven/BookHeaven.Domain
        mv temp/BookHeaven.Domain/* BookHeaven/BookHeaven.Domain/

    - name: Build Docker image
      run: docker build ./BookHeaven --build-arg GOOGLE_BOOKS_API_KEY=${{ secrets.GOOGLE_BOOKS_API_KEY }} --file BookHeaven/BookHeaven.Server/Dockerfile --tag ${{env.REGISTRY}}/${{ env.IMAGE_NAME }}:latest

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin

    - name: Push Docker image
      run: docker push ${{env.REGISTRY}}/${{ env.IMAGE_NAME }}:latest
